const States = [
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "South Carolina",
  "South Dakota",
  "Texas",
  "Virginia",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Puerto Rico",
  "Georgia",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maryland",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Florida",
  "Tennessee",
  "Utah",
  "Washington",
  "Connecticut",
  "Massachusetts",
  "New Jersey",
  "Maine",
  "Hawaii",
  "Vermont",
  "Virgin Islands",
  "American Samoa",
  "Rhode Island",
  "Delaware",
  "Guam",
  "District of Columbia",
];

export default States;
